version: '3'

services:
  api:
    container_name: api
    build:
      context: ./
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    command: yarn dev
    ports:
      - "3333:3333"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ETHEREAL_TEST_USER=libbie17@ethereal.email
      - ETHEREAL_TEST_PASS=Yt4c6CDUSxQXvtcvYe
    networks:
      - app-network
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:     
      - redisdata:/bitnami
    networks:
      - app-network  

networks:
  app-network:

volumes:
  nodemodules:
  redisdata: